version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: uploader-rabbitmq
    ports:
      - "5672:5672"   # AMQP protocol port
      - "15672:15672" # Management UI port
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin123
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - uploader-network

  minio:
    image: minio/minio
    container_name: uploader-minio
    ports:
      - "9000:9000"   # API port
      - "9001:9001"   # Console port
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin123
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - uploader-network

  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: uploader-nextjs
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - rabbitmq
      - minio
    networks:
      - uploader-network

networks:
  uploader-network:
    driver: bridge

volumes:
  rabbitmq_data:
  minio_data: